### ISSUE TITLE
voice masks broken

### ISSUE THREAD

**Issue by mqole** [impstation/imp-station-14#485]
## Description
They don't work.

**Reproduction**
put on a voice mask. it doesnt work.

**Comment by TGRCdev** [comment]
Voice masks appear to be working upstream as of commit [d871313899c27d14fd3472749be9117dc16a47c8](https://github.com/space-wizards/space-station-14/commit/d871313899c27d14fd3472749be9117dc16a47c8), so hopefully it will be fixed with the next upstream merge. If not, ping me
![image](https://github.com/user-attachments/assets/80df73e6-38fb-4a64-86fc-2dae14b56497)

**Comment by TGRCdev** [comment]
Was NOT fixed in the latest upstream merge, so it's probably an impstation-exclusive bug. guh.
