### ISSUE TITLE
Dealing with antags in low population settings feels awful

### ISSUE THREAD

**Issue by kipdotnet** [impstation/imp-station-14#768]
## Description

Lowpop is misery with the level of antags it rolls.

Round 1922 had 20-ish crew by my count, and two traitors, two sleeper agents, a thief, a revenant and a loneop, thats a quarter of the crew as antags, and a loneop and revenant on top of it. We had no security, and the only person on the station with access to a firearm was the captain. I really dont want to make this out as a security issue, because we didnt even have science and cargo staffed. 
Trying to deal with a loneop and a traitor with a china lake without any form of way to counteract it is agony. its miserable. its not fun at all.

Something really really needs to change, and I want to open a discussion here on what we could do at the very least because it drives me away from the game in the only real hours I have the free time to play.

**Reproduction**

view round 1922 replay

**Comment by kipdotnet** [comment]
I really dont know what could change. at the very least I dont think loneops and sleepers should be able to roll if theres no security present.

**Comment by TGRCdev** [comment]
Related to #569. We've been meaning to add a more relaxed lowpop gamemode, but I don't know enough about game presets to implement it

**Comment by mutanteggs** [comment]
I think keeping kessler is good, maybe knocking down the rate even more. It's cool to have a mode that just Is Hell, but rolling too much sucks ass. Removing it from lowpop is ideal though. I'm not sure I like the limited TC or blacklist, it feels really restricting to a traitor. 5 TC is still enough to get guns, to be loud, if you're smart about it, and I think I'm more into the main antagonist thief as a mechanical prevention of "going loud". I'd say maybe up the number to two if the main antagonist is going to be a pacifist with objectives to only steal, though? As for extended on low pop, I think it's fine. You can always cryo, you could always make fun, so on so on.

**Comment by kipdotnet** [comment]
Removing kessler is definitely an overstep, I thinm. It definitely shouldnt happen on atlas or reach though.

Points 1, 2, and 4 I agree on entirely. Just making the clake/bulldog out of reach would be plenty. Even if you have to break into the armory to get a gun that at least still leaves the door open behind you.

The issue that I have is less traitors being loud, and more that there are frequent situations where lethal force is nessecary with nobody on board with reasonable access to lethal weapons. Take a look at reach and tell me how someone with DAGD and a jugg suit is supposed to play out there :<

Thank you so much for looking into this. Youre the best forever

**Comment by hivehum** [comment]
kessler is already the lowest gamemode chance that is probably possible (1%, theres been some discussion on if dropping a gamemode below 1% does anything). kessler runs disproportionately often because it and survival are the only gamemodes without a minimum player population (traitor is 5 and everything else is 15+), and kessler has a shorter cooldown than survival, so adding cooldowns made the problem worse

**Comment by hivehum** [comment]
i would probably do no minimum pop for a lowpop traitor gamemode so we don't have situations where server pop is 4 at roundstart so kessler again

**Comment by Darkmajia** [comment]
im not 100% on the tc reduction or blacklist for lowpop traitor either, but there needs to be something limiting a traitors ability to just buy gloves or, god forbid, a surplus crate when nobodys equipped to deal with it. kessler staying in general is fine, i dont particularly think it should go, i've just heard complaints in-game about it that extend to "i don't think this would even be fun on highpop".

one thing i forgot to note about lowpop traitor that i was going to do was remove kill objectives from lowpop traitor since round removal is such a bigger deal, but theres also.. such limited objectives otherwise. its pretty much just steal objective and escape alive. so i'm not really sure about that either. lowpop traitor is such a hard thing to make enjoyable considering how badly it can go for everyone involved, or how nothing it can be with easy objectives

**Comment by kipdotnet** [comment]
These are good points....
I almost wonder if it would be better to just have maybe a slightly slowed down survival? Just have ventspawns serve as the killing factor and maybe have thieves running around in the background or something.

**Comment by kipdotnet** [comment]
Resolved by #872. Thank you dark ily forever
