### ISSUE TITLE
unidentified corpses from salvage should be ineligible for changelings/heretics

### ISSUE THREAD

**Issue by Darkmajia** [impstation/imp-station-14#856]
## Description
its far too easy for people to ignore actually playing the antag and beg for space corpses or, as salvager, just get space corpses yourself. as per the [wizden changeling proposal](https://docs.spacestation14.com/en/space-station-14/round-flow/proposals/changeling.html), unidentified corpses should spawn extremely bloated, and corpses past a certain amount of rot should be ineligible for changeling consumption and heretic rituals

salvage corpses will still be able to be gibbed for the organs required for heretic rituals, which is unfortunate, but i'm not sure what the best way to tackle this would be without diminishing the value salvagers can create for organ bounties

**Comment by AvianMaiden** [comment]
Rotting being a disqualifier for both sacrifices and feeding makes sense since the biomass has been consumed by the rot, leaving little for the ling or heretic to use. It (hopefully) would encourage players to be better about hunger management, not mass-murdering people only to get killed or have a locker full of bodies for later; it ideally would pace people to remain an active lurking threat without going on an early murder spree. It would tackle morgue feeding too. Sure, being a medical doctor and eating from the morgue works, but it doesn't become a massive fridge for any ling to chow down on.

**Comment by mqole** [comment]
>salvage corpses will still be able to be gibbed for the organs required for heretic rituals

as long as heretics still have kill objectives im less worried about this honestly

**Comment by Darkmajia** [comment]
only partially. i haven't done anything for heretics yet (though i'm unsure if i should)

**Comment by hivehum** [comment]
oops

**Comment by Darkmajia** [comment]
heretic has been derotated so im closing this
